// src/admin/dashboard/pages/settings/Elements/Fields/Commission/CategoryBasedCommission.tsx
import React, { useCallback, useMemo, useState } from '@wordpress/element';
import { __, sprintf } from '@wordpress/i18n';
import { MaskedInput, SimpleInput } from '@getdokan/dokan-ui';
import { debounce } from '@wordpress/compose';
import SquarePlus from '../../../../../../../components/Icons/SquarePlus';
import SquareMinus from '../../../../../../../components/Icons/SquareMinus';
import Plus from '../../../../../../../components/Icons/Plus';

interface Category {
    term_id: string | number;
    name: string;
    parent_id: string | number;
    parents: number[];
    children: Category[];
}

interface CommissionValues {
    all?: {
        percentage: string;
        flat: string;
    };
    items?: {
        [ categoryId: string ]: {
            percentage: string;
            flat: string;
        };
    };
}

interface SettingsProps {
    element: any;
    onValueChange: ( value: any ) => void;
}

interface SettingsElement {
    hook_key: string;
    children?: SettingsElement[];
    display?: boolean;
    value?: any;
    categories?: { [ key: string ]: Category };
}

// Extend Window interface for accounting library
declare global {
    interface Window {
        accounting: {
            unformat: ( value: string, decimal?: string ) => number;
            formatNumber: (
                value: string | number,
                precision?: number,
                thousand?: string,
                decimal?: string
            ) => string;
        };
    }
}

// Declare adminWithdrawData as a global variable
declare const adminWithdrawData: {
    currency: {
        symbol: string;
        thousand: string;
        decimal: string;
        precision: number;
    };
};

// Selector functions
const getSettingInChildren = (
    id: string,
    settings: SettingsElement[]
): SettingsElement | undefined => {
    for ( const setting of settings ) {
        if ( setting.hook_key === id ) {
            return setting;
        }
        if ( setting.children ) {
            const found = getSettingInChildren( id, setting.children );
            if ( found ) {
                return found;
            }
        }
    }
    return undefined;
};

export const getSettingById = (
    id: string,
    settings: SettingsElement[]
): SettingsElement | undefined => {
    return getSettingInChildren( id, settings );
};

const defaultCommission = { percentage: '0', flat: '2500' };

const CategoryBasedCommission = ( {
    element,
    onValueChange,
}: SettingsProps ) => {
    // Initialize commission state with proper memoization
    const initialCommission = useMemo( (): CommissionValues => {
        const commissionValues = element?.value || {};
        if ( Object.keys( commissionValues ).length > 0 ) {
            return commissionValues;
        }
        return {
            all: { ...defaultCommission },
            items: {},
        };
    }, [ element?.value ] );

    const [ commission, setCommission ] =
        useState< CommissionValues >( initialCommission );
    const [ expandedIds, setExpandedIds ] = useState<
        Array< string | number >
    >( [] );
    const [ allCategoryOpen, setAllCategoryOpen ] = useState( false );

    const { currency } = adminWithdrawData;
    const getCurrencySymbol = currency?.symbol;

    // Memoize categories to avoid dependency issues
    const categories = useMemo(
        () => element?.categories || {},
        [ element?.categories ]
    );

    // For now, use a default value since the SettingsElement doesn't have a value property
    const resetSubCategoryValue = false;

    // Fixed category building function
    const getCategories = useCallback(
        ( categoriesData: { [ key: string ]: Category } ) => {
            const result: Category[] = [];
            const categoryMap: { [ key: string ]: Category } = {};

            // First, create a map of all categories with empty children arrays
            for ( const termId in categoriesData ) {
                const category = categoriesData[ termId ];
                categoryMap[ termId ] = {
                    ...category,
                    children: [],
                };
            }

            // Build the nested structure - handle both parent_id and parents array
            for ( const termId in categoryMap ) {
                const category = categoryMap[ termId ];

                // Check if this is a top-level category
                const isTopLevel =
                    category.parent_id === '0' ||
                    category.parent_id === 0 ||
                    ! category.parent_id ||
                    ( category.parents && category.parents.length === 0 );

                if ( isTopLevel ) {
                    // This is a top-level category
                    result.push( category );
                } else {
                    // This is a child category - find its parent
                    const parentId = category.parent_id;
                    const parent = categoryMap[ parentId ];

                    if ( parent ) {
                        parent.children.push( category );
                    } else {
                        // If parent not found, treat as top-level
                        result.push( category );
                    }
                }
            }

            // Sort categories by name for consistent ordering
            const sortCategories = ( cats: Category[] ): Category[] => {
                return cats
                    .sort( ( a, b ) => a.name.localeCompare( b.name ) )
                    .map( ( cat ) => ( {
                        ...cat,
                        children: sortCategories( cat.children ),
                    } ) );
            };

            return sortCategories( result );
        },
        []
    );

    const getChildren = useCallback(
        ( parentId: string | number ) => {
            const categoriesArray = Object.values( categories );
            const children = categoriesArray.filter( ( item: any ) => {
                return (
                    item?.parent_id === parentId ||
                    item?.parents?.includes( Number( parentId ) )
                );
            } );
            return children.map( ( item: any ) => item?.term_id );
        },
        [ categories ]
    );

    const getCommissionValue = useCallback(
        ( commissionType: 'percentage' | 'flat', termId: string | number ) => {
            if ( commission?.items?.hasOwnProperty( termId ) ) {
                return commission?.items[ termId ][ commissionType ];
            }
            return commission?.all?.[ commissionType ];
        },
        [ commission ]
    );

    const unFormatValue = useCallback(
        ( inputValue: string ) => {
            if ( inputValue === '' ) {
                return inputValue;
            }

            if ( window.accounting ) {
                return String(
                    window.accounting.unformat(
                        inputValue,
                        currency?.decimal || '.'
                    )
                );
            }

            return String( inputValue ).replace( /[^0-9.-]/g, '' );
        },
        [ currency?.decimal ]
    );

    const formatValue = useCallback(
        ( inputValue: string ) => {
            if ( inputValue === '' ) {
                return inputValue;
            }

            if ( ! window.accounting ) {
                return inputValue;
            }

            return window.accounting.formatNumber(
                inputValue,
                currency?.precision,
                currency?.thousand,
                currency?.decimal
            );
        },
        [ currency?.precision, currency?.thousand, currency?.decimal ]
    );

    const validatePercentage = useCallback( ( percentage: string ) => {
        if ( percentage === '' ) {
            return percentage;
        }

        const numVal = Number( percentage );
        if ( numVal < 0 || numVal > 100 ) {
            return '';
        }

        return percentage;
    }, [] );

    const isEqual = useCallback( ( value1: any, value2: any ): boolean => {
        if ( value1 === value2 ) {
            return true;
        }

        if (
            value1 === null ||
            value2 === null ||
            value1 === undefined ||
            value2 === undefined
        ) {
            return false;
        }

        if ( typeof value1 !== typeof value2 ) {
            return false;
        }

        if ( typeof value1 === 'object' && typeof value2 === 'object' ) {
            const keys1 = Object.keys( value1 );
            const keys2 = Object.keys( value2 );

            if ( keys1.length !== keys2.length ) {
                return false;
            }

            for ( const key of keys1 ) {
                if ( ! keys2.includes( key ) ) {
                    return false;
                }
                if ( ! isEqual( value1[ key ], value2[ key ] ) ) {
                    return false;
                }
            }

            return true;
        }

        return false;
    }, [] );

    // Optimized debounced change handler
    const debouncedValueChange = useMemo(
        () =>
            debounce( ( ...args: unknown[] ) => {
                const updatedCommission = args[ 0 ] as CommissionValues;
                onValueChange( {
                    ...element,
                    value: updatedCommission,
                } );
            }, 500 ) as ( updatedCommission: CommissionValues ) => void,
        [ onValueChange, element ]
    );

    // Handle commission changes with immediate local update and debounced parent update
    const handleCommissionChange = useCallback(
        (
            inputValue: string,
            commissionType: 'percentage' | 'flat',
            termId: string | number
        ) => {
            let processedValue = inputValue;
            if ( commissionType === 'percentage' ) {
                processedValue = validatePercentage(
                    unFormatValue( inputValue )
                );
            } else {
                processedValue = unFormatValue( inputValue );
            }

            setCommission( ( prevCommission ) => {
                const newCommission = { ...prevCommission };
                const commissions = newCommission?.items
                    ? { ...newCommission.items }
                    : {};

                let data: { percentage: string; flat: string } =
                    resetSubCategoryValue
                        ? {
                              percentage: newCommission?.all?.percentage || '',
                              flat: newCommission?.all?.flat || '',
                          }
                        : { flat: '', percentage: '' };

                if ( commissions.hasOwnProperty( termId ) ) {
                    data = {
                        percentage: commissions[ termId ]?.percentage || '',
                        flat: commissions[ termId ]?.flat || '',
                    };
                }

                data[ commissionType ] = processedValue;
                commissions[ termId ] = data;

                newCommission.items = commissions;

                if ( resetSubCategoryValue ) {
                    const allNestedChildrenIds = getChildren( termId );
                    allNestedChildrenIds.forEach( ( id ) => {
                        if ( newCommission.items ) {
                            newCommission.items[ id ] = { ...data };
                        }
                    } );
                }

                // Remove categories with same values as 'all'
                if ( newCommission.items && newCommission.all ) {
                    Object.keys( newCommission.items ).forEach( ( key ) => {
                        if (
                            isEqual(
                                newCommission.items![ key ],
                                newCommission.all
                            )
                        ) {
                            delete newCommission.items![ key ];
                        }
                    } );
                }

                // Debounce the parent update
                debouncedValueChange( newCommission );

                return newCommission;
            } );
        },
        [
            resetSubCategoryValue,
            getChildren,
            isEqual,
            debouncedValueChange,
            validatePercentage,
            unFormatValue,
        ]
    );

    // Handle all category changes
    const handleAllCategoryChange = useCallback(
        ( inputValue: string, commissionType: 'percentage' | 'flat' ) => {
            let processedValue = inputValue;
            if ( commissionType === 'percentage' ) {
                processedValue = validatePercentage(
                    unFormatValue( inputValue )
                );
            } else {
                processedValue = unFormatValue( inputValue );
            }

            setCommission( ( prevCommission ) => {
                const newCommission = { ...prevCommission };
                newCommission.all = {
                    percentage: newCommission?.all?.percentage || '',
                    flat: newCommission?.all?.flat || '',
                    [ commissionType ]: processedValue,
                };

                if ( resetSubCategoryValue ) {
                    newCommission.items = {};
                }

                // Debounce the parent update
                debouncedValueChange( newCommission );

                return newCommission;
            } );
        },
        [
            resetSubCategoryValue,
            debouncedValueChange,
            validatePercentage,
            unFormatValue,
        ]
    );

    // Handle blur events for immediate updates
    const handleBlur = useCallback(
        (
            inputValue: string,
            commissionType: 'percentage' | 'flat',
            termId: string | number,
            isAllCategory: boolean = false
        ) => {
            if ( isAllCategory ) {
                handleAllCategoryChange( inputValue, commissionType );
            } else {
                handleCommissionChange( inputValue, commissionType, termId );
            }
        },
        [ handleAllCategoryChange, handleCommissionChange ]
    );

    const handleToggle = useCallback( ( id: string | number ) => {
        setExpandedIds( ( prev ) =>
            prev.includes( id )
                ? prev.filter( ( eid ) => eid !== id )
                : [ ...prev, id ]
        );
    }, [] );

    const renderCategoryRow = useCallback(
        ( cat: Category, level = 0 ) => {
            const hasChildren = !! cat.children && cat.children.length > 0;
            const isExpanded = expandedIds.includes( cat.term_id );
            const isAllCategory = cat.term_id === 'all';

            const renderIcon = () => {
                if ( isAllCategory ) {
                    return allCategoryOpen ? (
                        <SquareMinus color="#7047EB" />
                    ) : (
                        <SquarePlus />
                    );
                }

                if ( hasChildren ) {
                    if ( isExpanded ) {
                        return <SquareMinus color="#7047EB" />;
                    }
                    return <SquarePlus />;
                }

                return (
                    <SquarePlus className={ 'opacity-50 cursor-not-allowed' } />
                );
            };

            return (
                <div
                    key={ `${ cat.term_id }-${ level }` }
                    className="bg-white border-b border-[#E9E9E9] h-20"
                >
                    <div className="h-20 w-full flex items-center px-5">
                        <div
                            className="flex items-center"
                            style={ { paddingLeft: `${ level * 24 }px` } }
                        >
                            <button
                                type="button"
                                className={ `mr-3 p-1 text-[#828282] hover:text-[#575757] focus:!outline-none rounded transition-colors duration-150 ${
                                    ! hasChildren && ! isAllCategory
                                        ? 'opacity-50 cursor-not-allowed'
                                        : ''
                                }` }
                                onClick={ () => {
                                    if ( isAllCategory ) {
                                        setAllCategoryOpen(
                                            ( prev ) => ! prev
                                        );
                                    } else if ( hasChildren ) {
                                        handleToggle( cat.term_id );
                                    }
                                } }
                                disabled={ ! hasChildren && ! isAllCategory }
                            >
                                { renderIcon() }
                            </button>
                            <div className="flex items-center">
                                <span className="font-semibold text-[14px] text-[#575757]">
                                    { isAllCategory
                                        ? __( 'All Category', 'dokan-lite' )
                                        : cat.name }
                                </span>
                                <span className="ml-2 text-xs text-[#A5A5AA] bg-[#F1F1F4] px-2 py-0.5 rounded">
                                    { sprintf(
                                        /* translators: %s: category ID */
                                        __( '#%s', 'dokan-lite' ),
                                        cat.term_id
                                    ) }
                                </span>
                            </div>
                        </div>

                        <div className="flex items-center ml-auto gap-3">
                            <div className="flex items-center">
                                <div className="w-[142px]">
                                    <SimpleInput
                                        input={ {
                                            type: 'number',
                                        } }
                                        value={ formatValue(
                                            getCommissionValue(
                                                'percentage',
                                                cat.term_id
                                            ) || ''
                                        ) }
                                        addOnRight={
                                            <span className="text-[#575757] text-sm">
                                                %
                                            </span>
                                        }
                                        onChange={ ( e ) => {
                                            // Immediate local state update for better UX
                                            const value = e.target.value;
                                            if ( isAllCategory ) {
                                                setCommission( ( prev ) => ( {
                                                    ...prev,
                                                    all: {
                                                        percentage: value,
                                                        flat:
                                                            prev.all?.flat ||
                                                            '',
                                                    },
                                                } ) );
                                            } else {
                                                setCommission( ( prev ) => ( {
                                                    ...prev,
                                                    items: {
                                                        ...prev.items,
                                                        [ cat.term_id ]: {
                                                            percentage: value,
                                                            flat:
                                                                prev.items?.[
                                                                    cat.term_id
                                                                ]?.flat || '',
                                                        },
                                                    },
                                                } ) );
                                            }
                                        } }
                                        onBlur={ ( e ) =>
                                            handleBlur(
                                                e.target.value,
                                                'percentage',
                                                cat.term_id,
                                                isAllCategory
                                            )
                                        }
                                        className={ `w-full h-10 pl-6 pr-8 text-sm border ${
                                            cat.term_id === 23
                                                ? 'border-[#7047EB]'
                                                : 'border-[#E9E9E9]'
                                        } rounded-r-none bg-white transition-colors placeholder-[#828282] text-[#575757]` }
                                    />
                                </div>
                                <div className="mx-2">
                                    <Plus />
                                </div>
                                <div className="w-[120px]">
                                    <MaskedInput
                                        addOnLeft={
                                            <span className="text-[#575757] text-sm">
                                                { getCurrencySymbol }
                                            </span>
                                        }
                                        value={ formatValue(
                                            getCommissionValue(
                                                'flat',
                                                cat.term_id
                                            ) || ''
                                        ) }
                                        onChange={ ( e ) => {
                                            // Immediate local state update for better UX
                                            const value = e.target.value;
                                            if ( isAllCategory ) {
                                                setCommission( ( prev ) => ( {
                                                    ...prev,
                                                    all: {
                                                        ...prev.all,
                                                        flat: value,
                                                        percentage:
                                                            prev.all
                                                                ?.percentage ||
                                                            '',
                                                    },
                                                } ) );
                                            } else {
                                                setCommission( ( prev ) => ( {
                                                    ...prev,
                                                    items: {
                                                        ...prev.items,
                                                        [ cat.term_id ]: {
                                                            ...prev.items?.[
                                                                cat.term_id
                                                            ],
                                                            flat: value,
                                                            percentage:
                                                                prev.items?.[
                                                                    cat.term_id
                                                                ]?.percentage ||
                                                                '',
                                                        },
                                                    },
                                                } ) );
                                            }
                                        } }
                                        onBlur={ ( e ) =>
                                            handleBlur(
                                                e.target.value,
                                                'flat',
                                                cat.term_id,
                                                isAllCategory
                                            )
                                        }
                                        maskRule={ {
                                            numeral: true,
                                            delimiter: currency.thousand,
                                            numeralDecimalMark:
                                                currency.decimal,
                                            numeralDecimalScale:
                                                currency.precision,
                                        } }
                                        className={ `w-full h-10 pl-6 pr-3 text-sm border ${
                                            cat.term_id === 23
                                                ? 'border-[#7047EB]'
                                                : 'border-[#E9E9E9]'
                                        } rounded-r-[3px] bg-white focus:border-[#7047EB] focus:ring-1 focus:ring-[#7047EB] focus:ring-opacity-20 transition-colors placeholder-[#828282] text-[#575757]` }
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            );
        },
        [
            expandedIds,
            allCategoryOpen,
            handleToggle,
            getCommissionValue,
            formatValue,
            handleBlur,
            getCurrencySymbol,
            currency,
        ]
    );

    const renderCategories = useCallback(
        ( cats: Category[], level = 0 ): JSX.Element[] => {
            const result: JSX.Element[] = [];

            cats.forEach( ( cat ) => {
                // Render the current category
                result.push( renderCategoryRow( cat, level ) );

                // Render children if expanded and has children
                if (
                    cat.children &&
                    cat.children.length > 0 &&
                    expandedIds.includes( cat.term_id )
                ) {
                    // Recursively render children with increased level
                    result.push(
                        ...renderCategories( cat.children, level + 1 )
                    );
                }
            } );

            return result;
        },
        [ renderCategoryRow, expandedIds ]
    );

    const categoriesList = useMemo(
        () => getCategories( categories ),
        [ getCategories, categories ]
    );

    if ( ! element.display ) {
        return null;
    }

    return (
        <div className="w-full overflow-auto">
            { /* Header */ }
            <div className="h-16 flex items-center px-5">
                <div className="flex items-center">
                    <span className="font-normal text-xs text-[#828282] uppercase">
                        { __( 'Category Title', 'dokan-lite' ) }
                    </span>
                </div>
                <div className="flex items-center ml-auto gap-3">
                    <div className="flex items-center">
                        <div className="w-[142px]">
                            <span className="font-normal text-xs text-[#828282] uppercase">
                                { __( 'Percentage', 'dokan-lite' ) }
                            </span>
                        </div>
                        <div className="mx-2 w-4"></div>
                        <div className="w-[120px]">
                            <span className="font-normal text-xs text-[#828282] uppercase">
                                { __( 'Flat', 'dokan-lite' ) }
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            { /* Categories List */ }
            <div className="border-t border-[#E9E9E9]">
                { renderCategoryRow( {
                    term_id: 'all',
                    name: 'All Category',
                    parent_id: '0',
                    parents: [],
                    children: [],
                } ) }
                { allCategoryOpen && renderCategories( categoriesList ) }
            </div>
        </div>
    );
};

export default CategoryBasedCommission;

// src/admin/components/Commission/CategoryBasedCommission.vue
<template>
    <div class="dokan-category-commission">
        <div class='relative '>
        <div class='d-xs:hidden md:flex bg-gray-100 min-h-[3rem] text-gray-500 border-[0.957434px] border-b-0 items-center'>
            <div class='w-1/2 pl-3 flex h-[3rem] items-center border-r-[0.957434px]'>
                <p class='text-xs'>{{ __( 'Category', 'dokan-lite' ) }}</p>
            </div>

            <div class='flex w-1/2'>
                <div class='w-1/2 mr-20'>
                    <p class='text-xs text-center'>{{ __( 'Percentage', 'dokan-lite' ) }}</p>
                </div>
                <div class='w-1/2'>
                    <p class='text-xs text-center'>{{ __( 'Flat', 'dokan-lite' ) }}</p>
                </div>
            </div>
        </div>

        <div class='flex flex-col max-h-[500px] overflow-y-auto border-[1px] d-xs:text-[8px] sm:text-[14px] border-[#e9e9ea] border-solid' :class="! allCategroyEnabled ? 'border-b-[1px]': 'border-b-0'">
            <div class='flex flex-row'>
                <div class='flex flex-row w-1/2 items-center min-h-[3rem] border-0 !border-r-[1px] !border-b-[1px] border-[#e9e9ea] border-solid pl-[5px]'>
                    <button type='button' class='p-1 d-xs:pl-1 md:pl-4 bg-transparent bg-co border-none cursor-pointer' @click='()=>allCategroyEnabled = !allCategroyEnabled'>
                        <i class="far" :class='! allCategroyEnabled ? "fa-minus-square text-black" : "fa-plus-square text-[#4C19E6]"'></i>
                    </button>
                    <p class='d-xs:text-[8px] sm:text-[14px] !m-0'>{{__( 'All Categories', 'dokan-lite' )}}</p>
                </div>

                <div class='flex flex-row w-1/2 border-0 !border-b-[1px] border-[#e9e9ea] border-solid'>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                            <input
                                type="text"
                                class="wc_input_decimal !min-h-full focus:!shadow-none focus:border-transparent !border-0 !w-[100%] !pl-[5px] !pr-0 !pt-0 !pb-0"
                                id="percentage_commission"
                                name="percentage_commission"
                                ref='percentage'
                                :value="formatValue( commission.all.percentage )"
                                v-on:input="e => handleAllCategoryInput(e.target.value, 'percentage', commission.all.percentage )"
                                style="border: none !important;"
                            />
                            <div class='h-full d-xs:border-l-0 d-xs:border-r-0 md:border-l-[1px] md:!border-r-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ __( '%', 'dokan-lite' ) }}</span></div>
                        </div>
                    <div class='h-full border-l-[1px] !border-r-[1px] md:border-0 d-xs:bg-gray-100 md:bg-transparent  flex justify-center items-center'>
                            <span class='d-xs:p-1 md:p-2'>{{ __( '+', 'dokan-lite' ) }}</span>
                        </div>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                            <div class='h-full d-xs:border-r-0 d-xs:border-l-0 md:!border-r-[1px] md:border-l-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ getCurrencySymbol }}</span></div>
                            <input
                                type="text"
                                class="wc_input_price !min-h-full focus:!shadow-none !border-0 !w-[100%] d-xs:!pl-0 d-xs:!pr-[5px] d-xs:text-right md:text-left md:!pl-[5px] !pr-0 !pt-0 !pb-0"
                                id="fixed_commission"
                                name="fixed_commission"
                                ref='fixed'
                                :value="formatValue( commission.all.flat )"
                                v-on:input="e => handleAllCategoryInput(e.target.value, 'flat', commission.all.flat )"
                                style="border: none !important;"
                            />
                        </div>
                </div>
            </div>

            <div v-if='! allCategroyEnabled' class='flex flex-row border-0 !border-b-[1px] last:border-b-0 border-[#e9e9ea] border-solid' :class='showCatRow(item) ? "flex" : "hidden"' v-for='(item, index) in renderCategories' :key='item.term_id'>
                <div class='w-1/2 flex flex-row items-center min-h-[3rem] border-0 !border-r-[1px] border-[#e9e9ea] border-solid pl-[5px]'>
                    <div class='d-xs:flex h-1/2'>
                        <span v-for='parent_id in item.parents' :key='parent_id' class='d-xs:bg-[#e5e7eb] md:bg-transparent block h-full w-[1px] d-xs:ml-1'></span>
                    </div>
                    <button type='button' class='p-1 d-xs:pl-1 md:pl-6 bg-transparent border-none cursor-pointer' :disabled='!item.children.length' :class='!item.children.length ? "disabled:cursor-not-allowed text-gray-300" : "cursor-pointer text-[#7047EB]"' @click='()=> catRowClick( item, index )'>
                        <i class="far" :class='openRows.includes( Number( item.term_id ) ) ? "fa-minus-square text-black" : "fa-plus-square"'></i>
                    </button>
                    <p class='d-xs:text-[8px] sm:text-[14px] text-black !m-0'>
                        <span :title='item.name' v-html="item.name"></span>
                        <span class='d-xs:text-[6px] sm:text-[12px] text-gray-500' :title='__( "Category ID", "dokan" )'>#{{ item.term_id }}</span>
                    </p>
                </div>

                <div class='w-1/2 flex min-h-[3rem] border-0 border-solid border-[#e9e9ea]'>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                        <input
                            type="text"
                            class="wc_input_decimal !min-h-full focus:!shadow-none focus:border-transparent !border-0 !pl-[5px] !pr-0 !pt-0 !pb-0 !w-[100%]"
                            id="percentage_commission"
                            name="percentage_commission"
                            ref='percentage'
                            :value="formatValue( getCommissionValue( 'percentage', item.term_id ) )"
                            v-on:input="e => commissinItemHandler( e.target.value, 'percentage', item.term_id, getCommissionValue( 'percentage', item.term_id ) )"
                            style="border: none !important;"
                        />
                        <div class='h-full d-xs:border-l-0 d-xs:border-r-0 md:border-l-[1px] md:!border-r-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ __( '%', 'dokan-lite' ) }}</span></div>
                    </div>
                    <div class='h-full border-l-[1px] !border-r-[1px] md:border-0 d-xs:bg-gray-100 md:bg-transparent  flex justify-center items-center'>
                        <span class='d-xs:p-1 md:p-2'>{{ __( '+', 'dokan-lite' ) }}</span>
                    </div>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                        <div class='h-full d-xs:border-r-0 d-xs:border-l-0 md:!border-r-[1px] md:border-l-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ getCurrencySymbol }}</span></div>
                        <input
                            type="text"
                            class="wc_input_price !min-h-full focus:!shadow-none !border-0 d-xs:!pl-0 d-xs:!pr-[5px] d-xs:text-right md:text-left md:!pl-[5px] !pr-0 !pt-0 !pb-0 !w-[100%]"
                            id="fixed_commission"
                            name="fixed_commission"
                            ref='flat'
                            :value="formatValue( getCommissionValue( 'flat', item.term_id ) )"
                            v-on:input="e => commissinItemHandler( e.target.value, 'flat', item.term_id, getCommissionValue( 'flat', item.term_id ) )"
                            style="border: none !important;"
                        />
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</template>

<script>
import Debounce from "debounce";

export default {
        name: 'CategoryBasedCommission',
        props: {
            value: {
                type: Object,
                default: {
                    all: {
                        flat: '',
                        percentage: ''
                    },
                    items:{}
                }
            }
        },
        computed: {
            getCurrencySymbol() {
                return window.dokan.currency.symbol ? window.dokan.currency.symbol : '';
            },
        },
        data() {
            return {
                categories: [],
                renderCategories: [],
                openRows: [],
                allCategroyEnabled: true,
                commission: {
                    all: {
                        flat: '',
                        percentage: ''
                    },
                    items:{}
                }
            }
        },
        watch: {
            value( newValue ) {
                if ( typeof newValue === 'object' && newValue.hasOwnProperty('all') && typeof newValue.all === 'object' ) {
                    this.commission.all = newValue.all;
                }

                if ( typeof newValue === 'object' && newValue.hasOwnProperty( 'items' ) &&  typeof newValue.items === 'object') {
                    this.commission.items = newValue.items;
                }
            }
        },

        created() {
            if ( typeof this.value === 'object' && this.value.hasOwnProperty('all') && typeof this.value.all === 'object' ) {
                this.commission.all = this.value.all;
            }

            if ( typeof this.value === 'object' && this.value.hasOwnProperty( 'items' ) && ! Array.isArray( this.value.items ) ) {
                this.commission.items = this.value.items;
            } else {
                this.commission.items = {};
            }

            dokan.api.get('/products/multistep-categories').then( data => {
                if ( 'object' === typeof data) {
                    this.categories = data

                    this.renderCategories = Object.values( this.getCatgroies() );

                    if (this.commission.items && Object.values( this.commission.items ).length) {
                        this.allCategroyEnabled = false;
                    }
                }
            } );
        },
        methods: {
            getCatgroies() {
                const result = [];
                const categoryMap = {};

                // First, create a map of categories using term_id as the key
                for (const term_id in this.categories) {
                    categoryMap[term_id] = this.categories[term_id];
                }

                // Iterate through the categories to rearrange them
                for (const term_id in categoryMap) {
                    const category = categoryMap[term_id];

                    // If the category has a parent (parent_id is not 0), find its parent and insert it after the parent
                    if (category.parent_id !== '0') {
                        const parent = categoryMap[category.parent_id];
                        const parentIndex = result.indexOf(parent);

                        // Insert the child category right after its parent
                        result.splice(parentIndex + 1, 0, category);
                    } else {
                        // If it's a top-level category (parent_id is 0), add it to the result
                        result.push(category);
                    }
                }

                return result;
            },

            catRowClick( item, index, ) {
                if ( this.openRows.includes( Number( item.term_id ) ) ) {
                    // Remove the parent.
                    let index = this.openRows.indexOf(Number( item.term_id ));
                    this.openRows.splice(index, 1);

                    this.getChildren( item.term_id ).forEach( child => {
                        let index = this.openRows.indexOf(Number( child ));
                        -1 !== index ? this.openRows.splice(index, 1) : "";
                    } );
                } else {
                    this.openRows.push( Number( item.term_id ) );
                }
            },

            getChildren( parent_id ) {
                let categories = Object.values( this.categories );

                let children = categories.filter( item => {
                    return item.parents.includes( Number( parent_id ) );
                } );


                return children.map( item => {
                    return item.term_id;
                } );
            },

            showCatRow( item ) {
                if ( 0 === Number( item.parent_id ) ) {
                    return true;
                }

                return this.openRows.includes( Number( item.parent_id ) );
            },

            isOpen( id ) {
                this.openRows.push( Number( id ) )
            },

            getCommissionValue( comission_type, term_id ) {
                if ( this.commission.items.hasOwnProperty( term_id ) ) {
                    return this.commission.items[term_id][comission_type];
                }

                return this.commission.all[comission_type];
            },

            commissinItemHandler: Debounce( function( value, commission_type, term_id, oldValue = '' ) {
                if ( 'percentage' === commission_type ) {
                    value = this.validatePercentage( this.unFormatValue( value ) );
                } else {
                    value = this.unFormatValue( value );
                }

                let commissions = JSON.parse( JSON.stringify( this.commission.items ) );

                let data = JSON.parse( JSON.stringify( this.commission.all ) );

                if ( commissions.hasOwnProperty( term_id ) ) {
                    data = commissions[term_id];
                    data[commission_type] = value;

                    this.$set(this.commission.items, term_id, data);
                    this.updateChildCommissionValues( term_id, data );
                    this.deleteDuplicateCategories( this.commission.items );
                } else {
                    data[commission_type] = value;

                    this.$set(this.commission.items, term_id, data);
                    this.updateChildCommissionValues( term_id, data );
                    this.deleteDuplicateCategories( this.commission.items );
                }

                this.emitComponentChange( JSON.parse( JSON.stringify( this.commission ) ) )
            }, 700 ),

            handleAllCategoryInput: Debounce( function( value, commission_type, oldValue = '' ) {
                if ( 'percentage' === commission_type ) {
                    value = this.validatePercentage( this.unFormatValue( value ) );
                } else {
                    value = this.unFormatValue( value );
                }
                this.$set( this.commission.all, commission_type, value );
                this.$set(this.commission, 'items', {});

                this.emitComponentChange( JSON.parse( JSON.stringify( this.commission ) ) )
            }, 700 ),

            deleteDuplicateCategories( items ) {
                let self = this;
                Object.keys( items ).forEach( key => {
                    if ( self.isEqual( items[key], this.commission.all ) ) {
                        this.$delete(this.commission.items, key);
                    }
                } );
            },

            emitComponentChange( data ) {
                this.$emit( 'change', data );
            },

            isEqual(value1, value2) {
                let self = this;
                // Check if the values are strictly equal
                if (value1 === value2) return true;

                // Check if either value is null or undefined
                if (value1 == null || value2 == null) return false;

                // Check if the types are different
                if (typeof value1 !== typeof value2) return false;

                // Handle Date objects
                if (value1 instanceof Date && value2 instanceof Date) {
                    return value1.getTime() === value2.getTime();
                }

                // Handle Array objects
                if (Array.isArray(value1) && Array.isArray(value2)) {
                    if (value1.length !== value2.length) return false;
                    for (let i = 0; i < value1.length; i++) {
                        if (!self.isEqual(value1[i], value2[i])) return false;
                    }
                    return true;
                }

                // Handle plain objects
                if (typeof value1 === 'object' && typeof value2 === 'object') {
                    const keys1 = Object.keys(value1);
                    const keys2 = Object.keys(value2);

                    if (keys1.length !== keys2.length) return false;

                    for (let key of keys1) {
                        if (!keys2.includes(key)) return false;
                        if (!self.isEqual(value1[key], value2[key])) return false;
                    }

                    return true;
                }

                // For all other types, return false
                return false;
            },

            updateChildCommissionValues(parent_cat_id, commission_data) {
                let all_nested_children_ids = this.getChildren( parent_cat_id );
                let children = JSON.parse( JSON.stringify( this.commission.items ) );

                all_nested_children_ids.map( id => {
                    children[id] = commission_data;
                } );

                this.$set( this.commission, 'items', children );
            },

            unFormatValue: ( value ) => {
                if ( value === '' ) {
                    return value;
                }

                return String( accounting.unformat(value, dokan.currency.decimal) );
            },

            formatValue: ( value ) => {
                if ( value === '' ) {
                    return value;
                }

                return accounting.formatNumber( value, dokan.currency.precision, dokan.currency.thousand, dokan.currency.decimal );
            },

            validatePercentage( percentage ) {
                if ( percentage === '' ) {
                    return percentage;
                }

                if ( Number( percentage ) < 0 || Number( percentage ) > 100 ) {
                    percentage = '';
                }

                return percentage;
            },
        }
    }
</script>

<style scoped lang='less'>

</style>
