// src/admin/dashboard/pages/setup-guide/Elements/Fields/Commission/CategoryBasedCommission.tsx
import { useState } from '@wordpress/element';
import { __, sprintf } from '@wordpress/i18n';
import { MaskedInput } from '@getdokan/dokan-ui';
import { debounce } from '@wordpress/compose';
import { SettingsProps } from '../../../StepSettings';

const CategoryBasedCommission = ({ element, onValueChange }: SettingsProps) => {
    const { currency } = adminWithdrawData;
    const getCurrencySymbol = currency?.symbol;

    const getCategories = (categoriesData) => {
        const result = [];
        const categoryMap = {};

        // First, create a map of categories using term_id as the key
        for (const term_id in categoriesData) {
            categoryMap[term_id] = categoriesData[term_id];
        }

        // Iterate through the categories to rearrange them
        for (const term_id in categoryMap) {
            const category = categoryMap[term_id];

            // If the category has a parent (parent_id is not 0), find its parent and insert it after the parent
            if (category.parent_id !== '0') {
                const parent = categoryMap[category.parent_id];
                const parentIndex = result.indexOf(parent);

                // Insert the child category right after its parent
                result.splice(parentIndex + 1, 0, category);
            } else {
                // If it's a top-level category (parent_id is 0), add it to the result
                result.push(category);
            }
        }

        return result;
    };

    const categories = element?.categories || {};
    const commissionValues = element?.value || {};
    const resetCategoryVal = element?.reset_subcategory || 'on';
    const renderCategories = Object.values( getCategories( categories ) );
    const hasCommissionItems = Object.values( commissionValues?.items || {} ).length;
    const resetSubCategory = resetCategoryVal !== 'off';

    const [ openRows, setOpenRows ] = useState( [] );
    const [ commission, setCommission ] = useState( { ...commissionValues } );
    const [ allCategoryEnabled, setAllCategoryEnabled ] = useState( ! hasCommissionItems );

    // Toggle category row
    const catRowClick = (item) => {
        const termId = Number(item.term_id);

        if (openRows.includes(termId)) {
            // Remove the parent
            setOpenRows(prevRows => {
                const newRows = [...prevRows];
                const index = newRows.indexOf(termId);
                newRows.splice(index, 1);

                // Remove all children
                getChildren(item.term_id).forEach(child => {
                    const childIndex = newRows.indexOf(Number(child));
                    if (childIndex !== -1) {
                        newRows.splice(childIndex, 1);
                    }
                });

                return newRows;
            });
        } else {
            setOpenRows(prevRows => [...prevRows, termId]);
        }
    };

    // Get children of a category
    const getChildren = (parentId) => {
        const categoriesArray = Object.values( categories );

        const children = categoriesArray.filter(item => {
            return item.parents.includes(Number(parentId));
        });

        return children.map(item => item.term_id);
    };

    // Check if a category row should be shown
    const showCatRow = (item) => {
        if (Number(item.parent_id) === 0) {
            return true;
        }

        return openRows.includes(Number(item.parent_id));
    };

    // Get commission value for a category
    const getCommissionValue = ( commissionType, termId ) => {
        if ( commission?.items?.hasOwnProperty( termId ) ) {
            return commission?.items[ termId ][ commissionType ];
        }

        return commission?.all?.[ commissionType ];
    };

    // Handle commission change for a specific category
    const handleCommissionItemChange = debounce((value, commissionType, termId) => {
        if (commissionType === 'percentage') {
            value = validatePercentage(unFormatValue(value));
        } else {
            value = unFormatValue(value);
        }

        setCommission( prevCommission => {
            const newCommission = { ...prevCommission };
            const commissions = { ...newCommission?.items };

            let data = resetSubCategory
                ? { ...newCommission?.all }
                : { flat: '', percentage: '' };

            if (commissions.hasOwnProperty(termId)) {
                data = { ...commissions[termId] };
            }

            data[commissionType] = value;
            commissions[termId] = data;

            newCommission.items = commissions;

            // Update child categories if resetSubCategory is true
            if (resetSubCategory) {
                const allNestedChildrenIds = getChildren(termId);
                allNestedChildrenIds.forEach(id => {
                    newCommission.items[id] = { ...data };
                });
            }

            // Remove categories with same values as 'all'
            Object.keys(newCommission?.items).forEach(key => {
                if (isEqual(newCommission?.items[key], newCommission?.all)) {
                    delete newCommission?.items[key];
                }
            });

            return newCommission;
        });

        // Emit change to parent component
        onValueChange({
            ...element,
            value: {
                ...commission,
                items: { ...commission?.items, [termId]: {
                    ...commission?.items?.[termId] || commission?.all,
                    [commissionType]: value
                }}
            }
        });
    }, 700);

    // Handle all category commission change
    const handleAllCategoryChange = debounce((value, commissionType) => {
        if ( commissionType === 'percentage' ) {
            value = validatePercentage( unFormatValue( value ) );
        } else {
            value = unFormatValue( value );
        }

        setCommission(prevCommission => {
            const newCommission = { ...prevCommission };
            newCommission.all = { ...newCommission?.all, [commissionType]: value };

            if (resetSubCategory) {
                newCommission.items = {};
            }

            return newCommission;
        });

        onValueChange({
            ...element,
            value: {
                ...commission,
                all: { ...commission?.all, [commissionType]: value },
                items: resetSubCategory ? {} : commission?.items
            }
        });
    }, 700);

    // Format and unformat values
    const unFormatValue = (value) => {
        if ( value === '' ) {
            return value;
        }

        // Use accounting.js if available, otherwise simple conversion
        if ( window.accounting ) {
            return String( window.accounting.unformat( value, currency?.decimal || '.' ) );
        }

        return String(value).replace(/[^0-9.-]/g, '');
    };

    const formatValue = ( value ) => {
        if ( value === '' ) {
            return value;
        }

        return window.accounting.formatNumber( value, currency?.precision, currency?.thousand, currency?.decimal );
    };

    // Validate percentage value
    const validatePercentage = (percentage) => {
        if (percentage === '') {
            return percentage;
        }

        const numVal = Number(percentage);
        if (numVal < 0 || numVal > 100) {
            return '';
        }

        return percentage;
    };

    // Check if two objects are equal
    const isEqual = ( value1, value2 ) => {
        // Check if the values are strictly equal
        if (value1 === value2) return true;

        // Check if either value is null or undefined
        if (value1 == null || value2 == null) return false;

        // Check if the types are different
        if (typeof value1 !== typeof value2) return false;

        // Handle plain objects
        if (typeof value1 === 'object' && typeof value2 === 'object') {
            const keys1 = Object.keys(value1);
            const keys2 = Object.keys(value2);

            if (keys1.length !== keys2.length) return false;

            for (let key of keys1) {
                if (!keys2.includes(key)) return false;
                if (!isEqual(value1[key], value2[key])) return false;
            }

            return true;
        }

        // For all other types, return false
        return false;
    };

    if ( ! element.display ) {
        return null;
    }

    return (
        <div className="p-4 flex flex-col gap-y-4">
            { ( element?.title || element?.description ) && (
                <div className="flex-col flex gap-1">
                    <h2 className="text-sm leading-6 font-semibold text-gray-900">
                        {element?.title}
                    </h2>
                    <p className="text-sm font-normal text-[#828282]">
                        {element?.description}
                    </p>
                </div>
            )}

            <div className="relative">
                <div className="hidden md:flex bg-gray-100 min-h-[3rem] text-gray-500 border-[0.957434px] border-b-0 items-center">
                    <div className="w-1/2 pl-3 flex h-[3rem] items-center border-r-[0.957434px]">
                        <p className="text-xs">{__("Category", "dokan-lite")}</p>
                    </div>
                    <div className="flex w-1/2">
                        <div className="w-1/2 mr-20">
                            <p className="text-xs text-center">{__("Percentage", "dokan-lite")}</p>
                        </div>
                        <div className="w-1/2">
                            <p className="text-xs text-center">{__("Flat", "dokan-lite")}</p>
                        </div>
                    </div>
                </div>

                <div className={ `flex flex-col max-h-[500px] overflow-y-auto border-[1px] text-[14px] border-[#e9e9ea] border-solid ${ !allCategoryEnabled ? 'border-b-[1px]': 'border-b-0' }` }>
                    {/* All Categories Row */}
                    <div className="flex flex-row">
                        <div className="flex flex-row w-1/2 items-center min-h-[3rem] border-0 border-r-[1px] border-b-[1px] border-[#e9e9ea] border-solid pl-[5px]">
                            <button
                                type="button"
                                className="p-1 bg-transparent border-none cursor-pointer"
                                onClick={() => setAllCategoryEnabled(!allCategoryEnabled)}
                            >
                                <i className={`far ${ ! allCategoryEnabled ? "fa-minus-square text-black" : "fa-plus-square text-[#4C19E6]" }` }></i>
                            </button>
                            <p className="text-[14px] m-0">
                                { __( "All Categories", "dokan-lite" ) }
                            </p>
                        </div>

                        <div className="flex flex-row w-1/2 border-0 border-b-[1px] border-[#e9e9ea] border-solid">
                            <div className="w-1/2 flex justify-start items-center box-border">
                                <MaskedInput
                                    value={ formatValue( commission?.all?.percentage ) }
                                    onChange={ ( e ) => handleAllCategoryChange( e.target.value, 'percentage' ) }
                                    maskRule={ {
                                        numeral: true,
                                        delimiter: currency?.thousand ?? ',',
                                        numeralDecimalMark: currency?.decimal ?? '.',
                                        numeralDecimalScale: currency?.precision ?? 2,
                                    } }
                                    className={ `px-4 border-0 shadow-none focus:ring-0` }
                                />
                                <div className="h-full border-l-[1px] border-r-[1px] flex justify-center items-center bg-gray-100">
                                    <span className="pl-2 pr-2">{ __( "%", "dokan-lite" ) }</span>
                                </div>
                            </div>
                            <div className="h-full border-l-[1px] border-r-[1px] -ml-1 md:border-0 bg-transparent flex justify-center items-center">
                                <span className="p-2">{ __( "+" , "dokan-lite" ) }</span>
                            </div>
                            <div className="w-1/2 flex justify-start items-center box-border">
                                <div className="h-full border-r-[1px] border-l-[1px] flex justify-center items-center bg-gray-100">
                                    <span className="pl-2 pr-2">{ getCurrencySymbol }</span>
                                </div>
                                <MaskedInput
                                    // addOnLeft={ getCurrencySymbol }
                                    value={ formatValue( commission?.all?.flat ) }
                                    onChange={ ( e ) => handleAllCategoryChange( e.target.value, 'flat' ) }
                                    maskRule={ {
                                        numeral: true,
                                        delimiter: currency?.thousand ?? ',',
                                        numeralDecimalMark: currency?.decimal ?? '.',
                                        numeralDecimalScale: currency?.precision ?? 2,
                                    } }
                                    className={ `px-4 border-0 shadow-none focus:ring-0` }
                                />
                            </div>
                        </div>
                    </div>

                    {/* Category Rows */}
                    { ! allCategoryEnabled && renderCategories.map( ( item, index ) => (
                        showCatRow( item ) && (
                            <div
                                key={ item.term_id }
                                className="flex flex-row border-0 border-b-[1px] last:border-b-0 border-[#e9e9ea] border-solid"
                            >
                                <div className="w-1/2 flex flex-row items-center min-h-[3rem] border-0 border-r-[1px] border-[#e9e9ea] border-solid pl-[5px]">
                                    <div className="flex h-1/2">
                                        { item.parents.map( parentId => (
                                            <span
                                                key={ parentId }
                                                className="bg-transparent block h-full w-[1px] ml-1"
                                            ></span>
                                        ) ) }
                                    </div>
                                    <button
                                        type="button"
                                        className={ `p-1 bg-transparent border-none cursor-pointer ${ ! item.children.length ? "disabled:cursor-not-allowed text-gray-300" : "cursor-pointer text-[#4C19E6]" }` }
                                        onClick={ () => catRowClick( item ) }
                                        disabled={ ! item.children.length }
                                    >
                                        <i className={`far ${ openRows.includes( Number( item.term_id ) ) ? "fa-minus-square text-black" : "fa-plus-square" }` }></i>
                                    </button>
                                    <p className="text-[14px] text-black m-0">
                                        <span title={ item.name } dangerouslySetInnerHTML={{ __html: item.name }}></span>
                                        <span className="text-[12px] text-gray-500 ml-1" title={ __( "Category ID", "dokan" ) }>
                                            { sprintf( __( '#%s', 'dokan' ), item.term_id ) }
                                        </span>
                                    </p>
                                </div>

                                <div className="w-1/2 flex min-h-[3rem] border-0 border-solid border-[#e9e9ea]">
                                    <div className="w-1/2 flex justify-start items-center box-border">
                                        <MaskedInput
                                            // addOnLeft={ getCurrencySymbol }
                                            value={ formatValue( getCommissionValue( 'percentage', item.term_id ) ) }
                                            onChange={ ( e ) => handleCommissionItemChange( e.target.value, 'percentage', item.term_id ) }
                                            maskRule={ {
                                                numeral: true,
                                                delimiter: currency?.thousand ?? ',',
                                                numeralDecimalMark: currency?.decimal ?? '.',
                                                numeralDecimalScale: currency?.precision ?? 2,
                                            } }
                                            className={ `px-4 border-0 shadow-none focus:ring-0` }
                                        />
                                        <div className="h-full border-l-[1px] border-r-[1px] flex justify-center items-center bg-gray-100">
                                            <span className="pl-2 pr-2">{__("%", "dokan-lite")}</span>
                                        </div>
                                    </div>
                                    <div className="h-full border-l-[1px] border-r-[1px] -ml-1 md:border-0 bg-transparent flex justify-center items-center">
                                        <span className="p-2">{__("+" , "dokan-lite")}</span>
                                    </div>
                                    <div className="w-1/2 flex justify-start items-center box-border">
                                        <div className="h-full border-r-[1px] border-l-[1px] flex justify-center items-center bg-gray-100">
                                            <span className="pl-2 pr-2">{ getCurrencySymbol }</span>
                                        </div>
                                        <MaskedInput
                                            // addOnLeft={ getCurrencySymbol }
                                            value={ formatValue( getCommissionValue( 'flat', item.term_id ) ) }
                                            onChange={ ( e ) => handleCommissionItemChange( e.target.value, 'flat', item.term_id ) }
                                            maskRule={ {
                                                numeral: true,
                                                delimiter: currency?.thousand ?? ',',
                                                numeralDecimalMark: currency?.decimal ?? '.',
                                                numeralDecimalScale: currency?.precision ?? 2,
                                            } }
                                            className={ `px-4 border-0 shadow-none focus:ring-0` }
                                        />
                                    </div>
                                </div>
                            </div>
                        )
                    ) ) }
                </div>
            </div>
        </div>
    );
};

export default CategoryBasedCommission;

// src/admin/components/Commission/CategoryBasedCommission.vue
<template>
    <div class="dokan-category-commission">
        <div class='relative '>
        <div class='d-xs:hidden md:flex bg-gray-100 min-h-[3rem] text-gray-500 border-[0.957434px] border-b-0 items-center'>
            <div class='w-1/2 pl-3 flex h-[3rem] items-center border-r-[0.957434px]'>
                <p class='text-xs'>{{ __( 'Category', 'dokan-lite' ) }}</p>
            </div>

            <div class='flex w-1/2'>
                <div class='w-1/2 mr-20'>
                    <p class='text-xs text-center'>{{ __( 'Percentage', 'dokan-lite' ) }}</p>
                </div>
                <div class='w-1/2'>
                    <p class='text-xs text-center'>{{ __( 'Flat', 'dokan-lite' ) }}</p>
                </div>
            </div>
        </div>

        <div class='flex flex-col max-h-[500px] overflow-y-auto border-[1px] d-xs:text-[8px] sm:text-[14px] border-[#e9e9ea] border-solid' :class="! allCategroyEnabled ? 'border-b-[1px]': 'border-b-0'">
            <div class='flex flex-row'>
                <div class='flex flex-row w-1/2 items-center min-h-[3rem] border-0 !border-r-[1px] !border-b-[1px] border-[#e9e9ea] border-solid pl-[5px]'>
                    <button type='button' class='p-1 d-xs:pl-1 md:pl-4 bg-transparent bg-co border-none cursor-pointer' @click='()=>allCategroyEnabled = !allCategroyEnabled'>
                        <i class="far" :class='! allCategroyEnabled ? "fa-minus-square text-black" : "fa-plus-square text-[#4C19E6]"'></i>
                    </button>
                    <p class='d-xs:text-[8px] sm:text-[14px] !m-0'>{{__( 'All Categories', 'dokan-lite' )}}</p>
                </div>

                <div class='flex flex-row w-1/2 border-0 !border-b-[1px] border-[#e9e9ea] border-solid'>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                            <input
                                type="text"
                                class="wc_input_decimal !min-h-full focus:!shadow-none focus:border-transparent !border-0 !w-[100%] !pl-[5px] !pr-0 !pt-0 !pb-0"
                                id="percentage_commission"
                                name="percentage_commission"
                                ref='percentage'
                                :value="formatValue( commission.all.percentage )"
                                v-on:input="e => handleAllCategoryInput(e.target.value, 'percentage', commission.all.percentage )"
                                style="border: none !important;"
                            />
                            <div class='h-full d-xs:border-l-0 d-xs:border-r-0 md:border-l-[1px] md:!border-r-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ __( '%', 'dokan-lite' ) }}</span></div>
                        </div>
                    <div class='h-full border-l-[1px] !border-r-[1px] md:border-0 d-xs:bg-gray-100 md:bg-transparent  flex justify-center items-center'>
                            <span class='d-xs:p-1 md:p-2'>{{ __( '+', 'dokan-lite' ) }}</span>
                        </div>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                            <div class='h-full d-xs:border-r-0 d-xs:border-l-0 md:!border-r-[1px] md:border-l-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ getCurrencySymbol }}</span></div>
                            <input
                                type="text"
                                class="wc_input_price !min-h-full focus:!shadow-none !border-0 !w-[100%] d-xs:!pl-0 d-xs:!pr-[5px] d-xs:text-right md:text-left md:!pl-[5px] !pr-0 !pt-0 !pb-0"
                                id="fixed_commission"
                                name="fixed_commission"
                                ref='fixed'
                                :value="formatValue( commission.all.flat )"
                                v-on:input="e => handleAllCategoryInput(e.target.value, 'flat', commission.all.flat )"
                                style="border: none !important;"
                            />
                        </div>
                </div>
            </div>

            <div v-if='! allCategroyEnabled' class='flex flex-row border-0 !border-b-[1px] last:border-b-0 border-[#e9e9ea] border-solid' :class='showCatRow(item) ? "flex" : "hidden"' v-for='(item, index) in renderCategories' :key='item.term_id'>
                <div class='w-1/2 flex flex-row items-center min-h-[3rem] border-0 !border-r-[1px] border-[#e9e9ea] border-solid pl-[5px]'>
                    <div class='d-xs:flex h-1/2'>
                        <span v-for='parent_id in item.parents' :key='parent_id' class='d-xs:bg-[#e5e7eb] md:bg-transparent block h-full w-[1px] d-xs:ml-1'></span>
                    </div>
                    <button type='button' class='p-1 d-xs:pl-1 md:pl-6 bg-transparent border-none cursor-pointer' :disabled='!item.children.length' :class='!item.children.length ? "disabled:cursor-not-allowed text-gray-300" : "cursor-pointer text-[#7047EB]"' @click='()=> catRowClick( item, index )'>
                        <i class="far" :class='openRows.includes( Number( item.term_id ) ) ? "fa-minus-square text-black" : "fa-plus-square"'></i>
                    </button>
                    <p class='d-xs:text-[8px] sm:text-[14px] text-black !m-0'>
                        <span :title='item.name' v-html="item.name"></span>
                        <span class='d-xs:text-[6px] sm:text-[12px] text-gray-500' :title='__( "Category ID", "dokan" )'>#{{ item.term_id }}</span>
                    </p>
                </div>

                <div class='w-1/2 flex min-h-[3rem] border-0 border-solid border-[#e9e9ea]'>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                        <input
                            type="text"
                            class="wc_input_decimal !min-h-full focus:!shadow-none focus:border-transparent !border-0 !pl-[5px] !pr-0 !pt-0 !pb-0 !w-[100%]"
                            id="percentage_commission"
                            name="percentage_commission"
                            ref='percentage'
                            :value="formatValue( getCommissionValue( 'percentage', item.term_id ) )"
                            v-on:input="e => commissinItemHandler( e.target.value, 'percentage', item.term_id, getCommissionValue( 'percentage', item.term_id ) )"
                            style="border: none !important;"
                        />
                        <div class='h-full d-xs:border-l-0 d-xs:border-r-0 md:border-l-[1px] md:!border-r-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ __( '%', 'dokan-lite' ) }}</span></div>
                    </div>
                    <div class='h-full border-l-[1px] !border-r-[1px] md:border-0 d-xs:bg-gray-100 md:bg-transparent  flex justify-center items-center'>
                        <span class='d-xs:p-1 md:p-2'>{{ __( '+', 'dokan-lite' ) }}</span>
                    </div>
                    <div class='w-1/2 flex justify-start items-center box-border'>
                        <div class='h-full d-xs:border-r-0 d-xs:border-l-0 md:!border-r-[1px] md:border-l-[1px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100'><span class='d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2'>{{ getCurrencySymbol }}</span></div>
                        <input
                            type="text"
                            class="wc_input_price !min-h-full focus:!shadow-none !border-0 d-xs:!pl-0 d-xs:!pr-[5px] d-xs:text-right md:text-left md:!pl-[5px] !pr-0 !pt-0 !pb-0 !w-[100%]"
                            id="fixed_commission"
                            name="fixed_commission"
                            ref='flat'
                            :value="formatValue( getCommissionValue( 'flat', item.term_id ) )"
                            v-on:input="e => commissinItemHandler( e.target.value, 'flat', item.term_id, getCommissionValue( 'flat', item.term_id ) )"
                            style="border: none !important;"
                        />
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</template>

<script>
import Debounce from "debounce";

export default {
        name: 'CategoryBasedCommission',
        props: {
            value: {
                type: Object,
                default: {
                    all: {
                        flat: '',
                        percentage: ''
                    },
                    items:{}
                }
            }
        },
        computed: {
            getCurrencySymbol() {
                return window.dokan.currency.symbol ? window.dokan.currency.symbol : '';
            },
        },
        data() {
            return {
                categories: [],
                renderCategories: [],
                openRows: [],
                allCategroyEnabled: true,
                commission: {
                    all: {
                        flat: '',
                        percentage: ''
                    },
                    items:{}
                }
            }
        },
        watch: {
            value( newValue ) {
                if ( typeof newValue === 'object' && newValue.hasOwnProperty('all') && typeof newValue.all === 'object' ) {
                    this.commission.all = newValue.all;
                }

                if ( typeof newValue === 'object' && newValue.hasOwnProperty( 'items' ) &&  typeof newValue.items === 'object') {
                    this.commission.items = newValue.items;
                }
            }
        },

        created() {
            if ( typeof this.value === 'object' && this.value.hasOwnProperty('all') && typeof this.value.all === 'object' ) {
                this.commission.all = this.value.all;
            }

            if ( typeof this.value === 'object' && this.value.hasOwnProperty( 'items' ) && ! Array.isArray( this.value.items ) ) {
                this.commission.items = this.value.items;
            } else {
                this.commission.items = {};
            }

            dokan.api.get('/products/multistep-categories').then( data => {
                if ( 'object' === typeof data) {
                    this.categories = data

                    this.renderCategories = Object.values( this.getCatgroies() );

                    if (this.commission.items && Object.values( this.commission.items ).length) {
                        this.allCategroyEnabled = false;
                    }
                }
            } );
        },
        methods: {
            getCatgroies() {
                const result = [];
                const categoryMap = {};

                // First, create a map of categories using term_id as the key
                for (const term_id in this.categories) {
                    categoryMap[term_id] = this.categories[term_id];
                }

                // Iterate through the categories to rearrange them
                for (const term_id in categoryMap) {
                    const category = categoryMap[term_id];

                    // If the category has a parent (parent_id is not 0), find its parent and insert it after the parent
                    if (category.parent_id !== '0') {
                        const parent = categoryMap[category.parent_id];
                        const parentIndex = result.indexOf(parent);

                        // Insert the child category right after its parent
                        result.splice(parentIndex + 1, 0, category);
                    } else {
                        // If it's a top-level category (parent_id is 0), add it to the result
                        result.push(category);
                    }
                }

                return result;
            },

            catRowClick( item, index, ) {
                if ( this.openRows.includes( Number( item.term_id ) ) ) {
                    // Remove the parent.
                    let index = this.openRows.indexOf(Number( item.term_id ));
                    this.openRows.splice(index, 1);

                    this.getChildren( item.term_id ).forEach( child => {
                        let index = this.openRows.indexOf(Number( child ));
                        -1 !== index ? this.openRows.splice(index, 1) : "";
                    } );
                } else {
                    this.openRows.push( Number( item.term_id ) );
                }
            },

            getChildren( parent_id ) {
                let categories = Object.values( this.categories );

                let children = categories.filter( item => {
                    return item.parents.includes( Number( parent_id ) );
                } );


                return children.map( item => {
                    return item.term_id;
                } );
            },

            showCatRow( item ) {
                if ( 0 === Number( item.parent_id ) ) {
                    return true;
                }

                return this.openRows.includes( Number( item.parent_id ) );
            },

            isOpen( id ) {
                this.openRows.push( Number( id ) )
            },

            getCommissionValue( comission_type, term_id ) {
                if ( this.commission.items.hasOwnProperty( term_id ) ) {
                    return this.commission.items[term_id][comission_type];
                }

                return this.commission.all[comission_type];
            },

            commissinItemHandler: Debounce( function( value, commission_type, term_id, oldValue = '' ) {
                if ( 'percentage' === commission_type ) {
                    value = this.validatePercentage( this.unFormatValue( value ) );
                } else {
                    value = this.unFormatValue( value );
                }

                let commissions = JSON.parse( JSON.stringify( this.commission.items ) );

                let data = JSON.parse( JSON.stringify( this.commission.all ) );

                if ( commissions.hasOwnProperty( term_id ) ) {
                    data = commissions[term_id];
                    data[commission_type] = value;

                    this.$set(this.commission.items, term_id, data);
                    this.updateChildCommissionValues( term_id, data );
                    this.deleteDuplicateCategories( this.commission.items );
                } else {
                    data[commission_type] = value;

                    this.$set(this.commission.items, term_id, data);
                    this.updateChildCommissionValues( term_id, data );
                    this.deleteDuplicateCategories( this.commission.items );
                }

                this.emitComponentChange( JSON.parse( JSON.stringify( this.commission ) ) )
            }, 700 ),

            handleAllCategoryInput: Debounce( function( value, commission_type, oldValue = '' ) {
                if ( 'percentage' === commission_type ) {
                    value = this.validatePercentage( this.unFormatValue( value ) );
                } else {
                    value = this.unFormatValue( value );
                }
                this.$set( this.commission.all, commission_type, value );
                this.$set(this.commission, 'items', {});

                this.emitComponentChange( JSON.parse( JSON.stringify( this.commission ) ) )
            }, 700 ),

            deleteDuplicateCategories( items ) {
                let self = this;
                Object.keys( items ).forEach( key => {
                    if ( self.isEqual( items[key], this.commission.all ) ) {
                        this.$delete(this.commission.items, key);
                    }
                } );
            },

            emitComponentChange( data ) {
                this.$emit( 'change', data );
            },

            isEqual(value1, value2) {
                let self = this;
                // Check if the values are strictly equal
                if (value1 === value2) return true;

                // Check if either value is null or undefined
                if (value1 == null || value2 == null) return false;

                // Check if the types are different
                if (typeof value1 !== typeof value2) return false;

                // Handle Date objects
                if (value1 instanceof Date && value2 instanceof Date) {
                    return value1.getTime() === value2.getTime();
                }

                // Handle Array objects
                if (Array.isArray(value1) && Array.isArray(value2)) {
                    if (value1.length !== value2.length) return false;
                    for (let i = 0; i < value1.length; i++) {
                        if (!self.isEqual(value1[i], value2[i])) return false;
                    }
                    return true;
                }

                // Handle plain objects
                if (typeof value1 === 'object' && typeof value2 === 'object') {
                    const keys1 = Object.keys(value1);
                    const keys2 = Object.keys(value2);

                    if (keys1.length !== keys2.length) return false;

                    for (let key of keys1) {
                        if (!keys2.includes(key)) return false;
                        if (!self.isEqual(value1[key], value2[key])) return false;
                    }

                    return true;
                }

                // For all other types, return false
                return false;
            },

            updateChildCommissionValues(parent_cat_id, commission_data) {
                let all_nested_children_ids = this.getChildren( parent_cat_id );
                let children = JSON.parse( JSON.stringify( this.commission.items ) );

                all_nested_children_ids.map( id => {
                    children[id] = commission_data;
                } );

                this.$set( this.commission, 'items', children );
            },

            unFormatValue: ( value ) => {
                if ( value === '' ) {
                    return value;
                }

                return String( accounting.unformat(value, dokan.currency.decimal) );
            },

            formatValue: ( value ) => {
                if ( value === '' ) {
                    return value;
                }

                return accounting.formatNumber( value, dokan.currency.precision, dokan.currency.thousand, dokan.currency.decimal );
            },

            validatePercentage( percentage ) {
                if ( percentage === '' ) {
                    return percentage;
                }

                if ( Number( percentage ) < 0 || Number( percentage ) > 100 ) {
                    percentage = '';
                }

                return percentage;
            },
        }
    }
</script>

<style scoped lang='less'>

</style>
