// src/admin/dashboard/pages/setup-guide/Elements/Fields/Commission/CombineInput.tsx
import { useState, useEffect } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import { debounce } from 'lodash';
import { SettingsProps } from '../../StepSettings';

const CombineInput = ({ element, onValueChange }: SettingsProps) => {
    const [values, setValues] = useState({
        percentage: '',
        fixed: ''
    });

    // Get currency symbol
    const getCurrencySymbol = window.dokan?.currency?.symbol || '$';

    // Initialize values from element
    useEffect(() => {
        if (element) {
            setValues({
                percentage: element.percentage || '',
                fixed: element.fixed || ''
            });
        }
    }, [element]);

    // Handle change for percentage input
    const handlePercentageChange = debounce((value) => {
        // Validate percentage (0-100)
        let validatedValue = value;
        if (value !== '') {
            const numValue = parseFloat(unFormatValue(value));
            if (isNaN(numValue) || numValue < 0 || numValue > 100) {
                validatedValue = '';
            }
        }

        setValues(prev => ({
            ...prev,
            percentage: validatedValue
        }));

        // Emit change to parent component
        onValueChange({
            ...element,
            percentage: validatedValue,
            fixed: values.fixed
        });
    }, 500);

    // Handle change for fixed input
    const handleFixedChange = debounce((value) => {
        setValues(prev => ({
            ...prev,
            fixed: value
        }));

        // Emit change to parent component
        onValueChange({
            ...element,
            percentage: values.percentage,
            fixed: value
        });
    }, 500);

    // Format and unformat values
    const unFormatValue = (value) => {
        if (value === '') {
            return value;
        }

        // Use accounting.js if available, otherwise simple conversion
        if (window.accounting) {
            return String(window.accounting.unformat(value, window.dokan?.currency?.decimal || '.'));
        }

        return String(value).replace(/[^0-9.-]/g, '');
    };

    const formatValue = (value) => {
        if (value === '') {
            return value;
        }

        // Use accounting.js if available, otherwise simple formatting
        if (window.accounting) {
            return window.accounting.formatNumber(
                value,
                window.dokan?.currency?.precision || 2,
                window.dokan?.currency?.thousand || ',',
                window.dokan?.currency?.decimal || '.'
            );
        }

        return value;
    };

    if (!element.display) {
        return null;
    }

    return (
        <div className="p-4 flex flex-col gap-y-4">
            <div className="flex-col flex gap-1">
                <h2 className="text-sm leading-6 font-semibold text-gray-900">
                    {element?.title}
                </h2>
                <p className="text-sm font-normal text-[#828282]">
                    {element?.description}
                </p>
            </div>

            <div className="flex items-center space-x-2 border border-gray-300 rounded-md p-2">
                <div className="flex-1 flex items-center">
                    <input
                        type="text"
                        className="flex-1 p-2 border-0 focus:outline-none focus:ring-0"
                        value={formatValue(values.percentage)}
                        onChange={(e) => handlePercentageChange(e.target.value)}
                        placeholder="0"
                    />
                    <div className="px-2 py-1 bg-gray-100 rounded-md">
                        <span>%</span>
                    </div>
                </div>

                <div className="text-gray-500">+</div>

                <div className="flex-1 flex items-center">
                    <div className="px-2 py-1 bg-gray-100 rounded-md">
                        <span>{getCurrencySymbol}</span>
                    </div>
                    <input
                        type="text"
                        className="flex-1 p-2 border-0 focus:outline-none focus:ring-0"
                        value={formatValue(values.fixed)}
                        onChange={(e) => handleFixedChange(e.target.value)}
                        placeholder="0"
                    />
                </div>
            </div>
        </div>
    );
};

export default CombineInput;

// src/admin/components/CombineInput.vue
<template>
  <div
    class="d-xs:text-[8px] sm:text-[14px] d-xs:w-fit sm:w-fit md:w-auto h-[32px] flex d-xs:shadow-md md:shadow-none rounded-[5px]">
    <div
      class="md:shadow-md  border-[0.957434px] border-[#E9E9E9] d-xs:!border-r-0 md:!border-r-[0.957434px] rounded-[5px] d-xs:!rounded-r-none md:!rounded-r-[5px] !p-0 !m-0 w-[110px] flex justify-start items-center box-border">
      <input
        type="text"
        class="wc_input_decimal !border-none focus:!shadow-none !border-0 !w-[100%] !min-h-full !pl-2 !pr-0 !pt-0 !pb-0 min-w-[75px]"
        ref="percentage"
        :id="percentageId"
        :name="percentageName"
        v-model="percentage"
        v-on:input="onInput"
        style="border: none !important;"
      />
      <div
        class="d-xs:border-l-0 md:border-l-[0.957434px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100 !min-h-full">
        <span class="d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2">{{ __( '%', 'dokan-lite' ) }}</span></div>
    </div>
    <div class="d-xs:border-[0.957434px] md:border-0 d-xs:bg-gray-100 md:bg-transparent  flex justify-center items-center">
      <span class="d-xs:p-1 md:p-2">{{ __( '+', 'dokan-lite' ) }}</span>
    </div>
    <div
      class="md:shadow-md border-[0.957434px] d-xs:!border-l-0 md:!border-l-[0.957434px] rounded-[5px] d-xs:!rounded-l-none md:!rounded-l-[5px] !p-0 !m-0 w-[110px] flex justify-start items-center box-border">
      <div
        class="d-xs:border-r-0 md:border-r-[0.957434px] flex justify-center items-center d-xs:!bg-transparent md:!bg-gray-100 !min-h-full">
        <span class="d-xs:pl-1 d-xs:pr-1 md:pl-2 md:pr-2">{{ getCurrencySymbol }}</span></div>
      <input
        type="text"
        class="wc_input_price focus:!shadow-none !border-0 !w-[100%] !min-h-full !pl-2 !pr-0 !pt-0 !pb-0 min-w-[75px]"
        ref="fixed"
        :id="fixedId"
        :name="fixexName"
        v-model="fixed"
        v-on:input="onInput"
        style="border: none !important;"
      />
    </div>
  </div>
</template>

<script>
import Debounce from "debounce";

    export default {
        name: 'CombineInput',
        props: {
            fixedId: {
                type: String,
                default: 'fixed-val-id'
            },
            percentageId: {
                type: String,
                default: 'percentage-val-id'
            },
            fixexName: {
                type: String,
                default: 'fixed-val-name'
            },
            percentageName: {
                type: String,
                default: 'percentage-val-name'
            },
            value: {
                type: Object,
                default: {
                    fixed: '',
                    percentage: ''
                }
            },
        },
        data() {
            return {
                fixed: this.formatPositiveValue( this.value.fixed ) ?? '',
                percentage: this.formatPositiveValue( this.value.percentage ) ?? ''
            };
        },
        watch: {
            value: {
                handler(newVal, oldVal) {
                    let newPercentage = this.validatePercentage( newVal.percentage );
                    let oldPercentage = this.validatePercentage( oldVal.percentage );

                    if ( ! newPercentage || '' === newPercentage || Number( newPercentage ) < 0 || Number( newPercentage ) > 100 ) {
                        newPercentage = oldPercentage;
                    }

                    this.fixed = this.formatPositiveValue( newVal.fixed );
                    this.percentage = this.formatPositiveValue( newPercentage );
                },
                deep: true
            }
        },
        methods: {
            validatePercentage( percentage ) {
                if ( Number( percentage ) < 0 || Number( percentage ) > 100 ) {
                    percentage = '';
                }

                return percentage;
            },
            onInput: Debounce( function() {
                let self = this;
                let data = {
                        fixed: self.fixed ? accounting.unformat(self.fixed, dokan.currency.decimal) : '',
                        percentage: self.percentage ? accounting.unformat(self.percentage, dokan.currency.decimal): ''
                    };

                this.$emit('change', data);
            }, 500 ),

            formatPositiveValue: ( value ) => {
                if ( value === '' ) {
                    return value;
                }

                return accounting.formatNumber( value, dokan.currency.precision, dokan.currency.thousand, dokan.currency.decimal );
            },
        },
        computed:{
            getCurrencySymbol() {
                return window.dokan.currency.symbol;
            }
        }
    };
</script>

<style scoped lang="less">
</style>
